### ISSUE TITLE
The shit doesn't work

### ISSUE THREAD

**Issue by suburbGira** [KemyszPL/KromerApp#2]
The shit doesn't work

**Comment by KemyszPL** [comment]
well then make it work and create a pull request you twat!!!!!!

**Comment by suburbGira** [comment]
i don't know how to write android apps!!!!!!!!!! or backends!!!!!!!!!!!!!!

**Comment by suburbGira** [comment]
There it's your skissue now

**Comment by KemyszPL** [comment]
Issue creator refused to purchase me a new keyboard earlier to continue development; closed.
![image](https://github.com/KemyszPL/KromerApp/assets/40953832/b4914239-8fb5-44cd-8aa1-d1f665cf32b5)

**Comment by suburbGira** [comment]
i don't have the available funds!!!!! £20 is a lot
